-- =====================================================
-- 第一步：清理所有相关车位数据（避免ID冲突）
-- =====================================================

-- 开始清理事务
BEGIN

-- 1. 清理车位分布记录
DELETE FROM PARKING_SPACE_DISTRIBUTION WHERE AREA_ID IN (1001, 1002, 1003);
DBMS_OUTPUT.PUT_LINE('已清理车位分布记录');

-- 2. 清理测试车位信息
DELETE FROM PARKING_SPACE WHERE PARKING_SPACE_ID BETWEEN 1001 AND 1120;
DELETE FROM PARKING_SPACE WHERE PARKING_SPACE_ID BETWEEN 2001 AND 2096;
DELETE FROM PARKING_SPACE WHERE PARKING_SPACE_ID BETWEEN 3001 AND 3144;
DBMS_OUTPUT.PUT_LINE('已清理测试车位信息');

-- 3. 清理停车场费用信息
DELETE FROM PARKING_LOT WHERE AREA_ID IN (1001, 1002, 1003);
DBMS_OUTPUT.PUT_LINE('已清理停车场费用信息');

-- 4. 清理停车场区域
DELETE FROM AREA WHERE AREA_ID IN (1001, 1002, 1003);
DBMS_OUTPUT.PUT_LINE('已清理停车场区域');

-- 提交清理操作
COMMIT;
DBMS_OUTPUT.PUT_LINE('==========================================');
DBMS_OUTPUT.PUT_LINE('✅ 历史车位数据清理完成！');
DBMS_OUTPUT.PUT_LINE('==========================================');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('❌ 清理过程中发生错误: ' || SQLERRM);
        ROLLBACK;
        RAISE;

END;
/

-- =====================================================
-- 第二步：创建新的车位基础数据
-- =====================================================

-- 1. 创建停车场区域
INSERT INTO AREA (AREA_ID, ISEMPTY, AREA_SIZE, CATEGORY) VALUES (1001, 1, 5000, 'PARKING');
INSERT INTO AREA (AREA_ID, ISEMPTY, AREA_SIZE, CATEGORY) VALUES (1002, 1, 4000, 'PARKING');
INSERT INTO AREA (AREA_ID, ISEMPTY, AREA_SIZE, CATEGORY) VALUES (1003, 1, 6000, 'PARKING');

-- 2. 创建停车场费用信息
INSERT INTO PARKING_LOT (AREA_ID, PARKING_FEE) VALUES (1001, 5.00);
INSERT INTO PARKING_LOT (AREA_ID, PARKING_FEE) VALUES (1002, 6.00);
INSERT INTO PARKING_LOT (AREA_ID, PARKING_FEE) VALUES (1003, 4.00);

-- 3. 创建车位信息
-- 停车场1001（120个车位，全部空闲）
BEGIN
    FOR i IN 1001..1120 LOOP
        INSERT INTO PARKING_SPACE (PARKING_SPACE_ID, OCCUPIED) VALUES (i, 0);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('已创建停车场1001的120个车位');
END;
/

-- 停车场1002（96个车位，全部空闲）
BEGIN
    FOR i IN 2001..2096 LOOP
        INSERT INTO PARKING_SPACE (PARKING_SPACE_ID, OCCUPIED) VALUES (i, 0);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('已创建停车场1002的96个车位');
END;
/

-- 停车场1003（144个车位，全部空闲）
BEGIN
    FOR i IN 3001..3144 LOOP
        INSERT INTO PARKING_SPACE (PARKING_SPACE_ID, OCCUPIED) VALUES (i, 0);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('已创建停车场1003的144个车位');
END;
/

-- 4. 创建车位分布记录（关联区域与车位）
-- 停车场1001的车位分布（120个）
BEGIN
    FOR i IN 1001..1120 LOOP
        INSERT INTO PARKING_SPACE_DISTRIBUTION (AREA_ID, PARKING_SPACE_ID) VALUES (1001, i);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('已创建停车场1001的车位分布记录');
END;
/

-- 停车场1002的车位分布（96个）
BEGIN
    FOR i IN 2001..2096 LOOP
        INSERT INTO PARKING_SPACE_DISTRIBUTION (AREA_ID, PARKING_SPACE_ID) VALUES (1002, i);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('已创建停车场1002的车位分布记录');
END;
/

-- 停车场1003的车位分布（144个）
BEGIN
    FOR i IN 3001..3144 LOOP
        INSERT INTO PARKING_SPACE_DISTRIBUTION (AREA_ID, PARKING_SPACE_ID) VALUES (1003, i);
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('已创建停车场1003的车位分布记录');
END;
/

-- 提交事务
COMMIT;

-- =====================================================
-- 第三步：数据验证和统计
-- =====================================================

-- 显示创建结果
SELECT '车位数据初始化完成！' AS MESSAGE FROM DUAL;
SELECT '总车位数：360个（1001:120个, 1002:96个, 1003:144个）' AS SUMMARY FROM DUAL;

-- 验证清理结果（应该都是0）
SELECT '=== 清理验证（应该都是0） ===' AS MESSAGE FROM DUAL;

SELECT 
    '停车场区域',
    COUNT(*)
FROM AREA WHERE AREA_ID IN (1001, 1002, 1003)
UNION ALL
SELECT 
    '车位信息',
    COUNT(*)
FROM PARKING_SPACE WHERE PARKING_SPACE_ID BETWEEN 1001 AND 3144
UNION ALL
SELECT 
    '车位分布',
    COUNT(*)
FROM PARKING_SPACE_DISTRIBUTION WHERE AREA_ID IN (1001, 1002, 1003)
UNION ALL
SELECT 
    '停车场费用',
    COUNT(*)
FROM PARKING_LOT WHERE AREA_ID IN (1001, 1002, 1003);

-- 停车场状态统计
SELECT '=== 停车场状态统计 ===' AS MESSAGE FROM DUAL;
SELECT 
    '停车场1001' AS PARKING_LOT,
    COUNT(*) AS TOTAL_SPACES,
    SUM(CASE WHEN ps.OCCUPIED = 0 THEN 1 ELSE 0 END) AS AVAILABLE_SPACES,
    SUM(CASE WHEN ps.OCCUPIED = 1 THEN 1 ELSE 0 END) AS OCCUPIED_SPACES,
    ROUND(SUM(CASE WHEN ps.OCCUPIED = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS OCCUPANCY_RATE,
    (SELECT PARKING_FEE FROM PARKING_LOT WHERE AREA_ID = 1001) AS PARKING_FEE
FROM PARKING_SPACE_DISTRIBUTION psd
JOIN PARKING_SPACE ps ON psd.PARKING_SPACE_ID = ps.PARKING_SPACE_ID
WHERE psd.AREA_ID = 1001
GROUP BY psd.AREA_ID
UNION ALL
SELECT 
    '停车场1002' AS PARKING_LOT,
    COUNT(*) AS TOTAL_SPACES,
    SUM(CASE WHEN ps.OCCUPIED = 0 THEN 1 ELSE 0 END) AS AVAILABLE_SPACES,
    SUM(CASE WHEN ps.OCCUPIED = 1 THEN 1 ELSE 0 END) AS OCCUPIED_SPACES,
    ROUND(SUM(CASE WHEN ps.OCCUPIED = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS OCCUPANCY_RATE,
    (SELECT PARKING_FEE FROM PARKING_LOT WHERE AREA_ID = 1002) AS PARKING_FEE
FROM PARKING_SPACE_DISTRIBUTION psd
JOIN PARKING_SPACE ps ON psd.PARKING_SPACE_ID = ps.PARKING_SPACE_ID
WHERE psd.AREA_ID = 1002
GROUP BY psd.AREA_ID
UNION ALL
SELECT 
    '停车场1003' AS PARKING_LOT,
    COUNT(*) AS TOTAL_SPACES,
    SUM(CASE WHEN ps.OCCUPIED = 0 THEN 1 ELSE 0 END) AS AVAILABLE_SPACES,
    SUM(CASE WHEN ps.OCCUPIED = 1 THEN 1 ELSE 0 END) AS OCCUPIED_SPACES,
    ROUND(SUM(CASE WHEN ps.OCCUPIED = 1 THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS OCCUPANCY_RATE,
    (SELECT PARKING_FEE FROM PARKING_LOT WHERE AREA_ID = 1003) AS PARKING_FEE
FROM PARKING_SPACE_DISTRIBUTION psd
JOIN PARKING_SPACE ps ON psd.PARKING_SPACE_ID = ps.PARKING_SPACE_ID
WHERE psd.AREA_ID = 1003
GROUP BY psd.AREA_ID;

-- 车位分布详情
SELECT '=== 车位分布详情 ===' AS MESSAGE FROM DUAL;
SELECT 
    psd.AREA_ID,
    COUNT(*) AS TOTAL_SPACES,
    SUM(CASE WHEN ps.OCCUPIED = 0 THEN 1 ELSE 0 END) AS AVAILABLE_SPACES,
    SUM(CASE WHEN ps.OCCUPIED = 1 THEN 1 ELSE 0 END) AS OCCUPIED_SPACES
FROM PARKING_SPACE_DISTRIBUTION psd
JOIN PARKING_SPACE ps ON psd.PARKING_SPACE_ID = ps.PARKING_SPACE_ID
WHERE psd.AREA_ID IN (1001, 1002, 1003)
GROUP BY psd.AREA_ID
ORDER BY psd.AREA_ID;

-- 各停车场容量统计
SELECT '=== 各停车场容量统计 ===' AS MESSAGE FROM DUAL;
SELECT 
    AREA_ID,
    CASE 
        WHEN AREA_ID = 1001 THEN '停车场1001'
        WHEN AREA_ID = 1002 THEN '停车场1002'
        WHEN AREA_ID = 1003 THEN '停车场1003'
    END AS PARKING_NAME,
    (SELECT COUNT(*) FROM PARKING_SPACE_DISTRIBUTION WHERE AREA_ID = a.AREA_ID) AS TOTAL_SPACES,
    (SELECT AREA_SIZE FROM AREA WHERE AREA_ID = a.AREA_ID) AS AREA_SIZE,
    (SELECT PARKING_FEE FROM PARKING_LOT WHERE AREA_ID = a.AREA_ID) AS PARKING_FEE
FROM AREA a
WHERE AREA_ID IN (1001, 1002, 1003)
ORDER BY AREA_ID;

SELECT '==========================================' AS MESSAGE FROM DUAL;
SELECT '✅ 车位数据初始化脚本执行完成！' AS MESSAGE FROM DUAL;
SELECT '✅ 总共创建360个车位（1001:120个, 1002:96个, 1003:144个）' AS SUMMARY FROM DUAL;
SELECT '==========================================' AS MESSAGE FROM DUAL;