BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE EVENT_ID_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN -- 序列已存在的错误码
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE COLLABORATION_ID_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE STAFF_ID_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE TRIGGER EVENT_ID_TRG
    BEFORE INSERT ON EVENT
    FOR EACH ROW
BEGIN
    IF :NEW.EVENT_ID IS NULL THEN
        SELECT EVENT_ID_SEQ.NEXTVAL INTO :NEW.EVENT_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER COLLABORATION_ID_TRG
    BEFORE INSERT ON COLLABORATION
    FOR EACH ROW
BEGIN
    IF :NEW.COLLABORATION_ID IS NULL THEN
        SELECT COLLABORATION_ID_SEQ.NEXTVAL INTO :NEW.COLLABORATION_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER STAFF_ID_TRG
    BEFORE INSERT ON STAFF
    FOR EACH ROW
BEGIN
    IF :NEW.STAFF_ID IS NULL THEN
        SELECT STAFF_ID_SEQ.NEXTVAL INTO :NEW.STAFF_ID FROM DUAL;
    END IF;
END;
/

COMMIT;